version: "2"

services:
  db:
    image: mysql:8.0.23
    container_name: mysql
    ports:
      - "13306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
        - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
